### PR TITLE
Fix bug where post meta may not save

### LINKED ISSUE #674: Meta update issue from consecutive calls to `usePostMetaValue()` setters
### Description of the bug

When making consecutive calls to `usePostMetaValue()` setters within the same procedure (render, callback, effect, etc), to update different meta on the same post, later calls will overwrite updates from earlier calls.

## Cause

The setter from `usePostMetaValue()` [updates all meta on the post](https://github.com/alleyinteractive/alley-scripts/blob/333817d86a8e7266121cad2053fca0b95d48157c/packages/block-editor-tools/src/hooks/use-post-meta-value/index.js#L27), by spreading the full object that it has in memory and only changing the key that it cares about. The problem that comes up from subsequent calls in the same procedure is that the full meta object that it has in memory is outdated; it won't get updated until the next render.

### Steps To Reproduce

This is best explained through a specific example:

```jsx
function Counter() {
  const [meta1 = 0, setMeta1] = usePostMetaValue('meta_1');
  const [meta2 = 0, setMeta2] = usePostMetaValue('meta_2');

  function updateMeta() {
    setMeta1(+meta1 + 1); // this doesn't save...
    setMeta2(+meta2 + 1); // ... because this overrides it.
  }

  return (
    <div>
      <h2>Meta 1: {meta1}</h2>
      <h2>Meta 2: {meta2}</h2>

      <button onClick={updateMeta}>+</button>
    </div>
  );
}
```

In this example, when the button is clicked, `meta2` will increment, but `meta1` will not. Better said, `meta1` updates and then `meta2` immediately overwrites that value.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mboynes**
Allows `usePostMeta` and `usePostMetaValue` setter functions to accept a callable, which would accept the current meta value(s) and return updated values, similarly to how `useState()` works.

Resolves #674.

### CODE REVIEW

File: packages/block-editor-tools/src/hooks/use-post-meta/index.js [hunk 1]
```diff
@@ -30,10 +43,19 @@ const usePostMeta = (postType = null, postId = null) => {
...
+   *
+   * @param {object|function} next - A new value for meta or a function that takes the current value
+   *                                 and returns a new value.
    */
-  const setMetaSafe = (next) => setMeta({ ...next });
+  const setMetaSafe = (next) => {
+    if (typeof next === 'object') {
+      setMeta({ ...next });
+    } else if (typeof next === 'function') {
+      setMeta({ ...next(getLatestMeta()) });
```
Comment (kevinfodness) [inline packages/block-editor-tools/src/hooks/use-post-meta/index.js:56]: Why not make this the default behavior? My concern is that by making this opt-in, by providing a function, that most users won't know that they need to do that in order to ensure their changes are saving properly and not overwriting existing in-progress meta updates. The current API behaves similarly to both `useState` (for working with a single value) and `setAttributes` (for working with an augmented object of data). What would be the harm in changing the implementation under the hood to always use the get latest meta function and otherwise keep these hooks unchanged?

Comment (mboynes) [reply packages/block-editor-tools/src/hooks/use-post-meta/index.js:56]: I don't know how we would make that work... ? As written, I made `usePostMetaValue()` always work this way, but I don't know how we might do that with `usePostMeta()` since it is always setting a full object, and therefore the responsibility of the implementing component or hook to get the latest meta. My point may not be clear 😄, so simply put: what would that code look like?

Comment (kevinfodness) [reply packages/block-editor-tools/src/hooks/use-post-meta/index.js:56]: Ah, I see what you mean, and how that would be a breaking change. `setAttributes` lets you provide a partial change where it inherits the current state and then augments it. Alternately, could we set up `usePostMetaValue` to work in that way without changing the default behavior for `usePostMeta`? Using that approach:

1. We would keep the changes to `usePostMeta` as you have written them where you can provide a function as the value.
2. The implementation of `usePostMetaValue` would change to always pass a function as the value to `usePostMeta` so that it augments existing state.

This would prevent the need for implementers to change how they are using `usePostMetaValue`, would preserve the ability to set the entire meta object via `usePostMeta`, and would provide an option for users to treat `usePostMeta` like `setAttributes` by using a function to do a partial update if they so chose.

Comment (kevinfodness) [reply packages/block-editor-tools/src/hooks/use-post-meta/index.js:56]: Re-reading the diff for `usePostMetaValue` - I think it's actually already working this way, yes?

Comment (mboynes) [reply packages/block-editor-tools/src/hooks/use-post-meta/index.js:56]: Yep, that's exactly what I did. And it now also accepts a function so it really works just like `useState()` et al

Comment (mboynes) [reply packages/block-editor-tools/src/hooks/use-post-meta/index.js:56]: I'm going to update all the docs to reflect and highlight these changes

Comment (kevinfodness) [reply packages/block-editor-tools/src/hooks/use-post-meta/index.js:56]: Fantastic, thanks!

**Review by kevinfodness — APPROVED** [review]
🍣

**Comment by mboynes** [comment]
@kevinfodness wanna give the docs a quick read?

**Review by kevinfodness — APPROVED** [review]
Doc updates look great - thanks! 🍣
