### PR TITLE
fix: export missing useBlockName and useParentClientId hooks

### LINKED ISSUE #763: `useBlockName` is not exported
### Description of the bug

Importing and using the `useBlockName` hook results in an error.

```
Uncaught TypeError: (0 , f.useBlockName) is not a function
```

After seeing this error, I notice the hook is not exported in `packages/block-editor-tools/src/hooks/index.js`.

### Steps To Reproduce

```js
import { useBlockName } from '@alleyinteractive/block-editor-tools';
const blockName = useBlockName(clientId);
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gabrielLAraujo**
Fixes issue where importing useBlockName hook resulted in 'is not a function' error.

## Problem
The useBlockName and useParentClientId hooks were implemented but not exported from the main hooks index file.

## Solution
- Added missing exports for useBlockName and useParentClientId hooks
- Fixed tsconfig.json to reference local tsconfig base file
- Maintained alphabetical order of exports

## Files Changed
- packages/block-editor-tools/src/hooks/index.js
- packages/block-editor-tools/tsconfig.json

This is a bug fix that resolves the import issue without breaking changes.

Fixes #763

### CODE REVIEW

File: packages/block-editor-tools/src/hooks/index.js [hunk 1]
```diff
@@ -1,20 +1,22 @@
...
-export { default as useParentBlockAttributes } from './use-parent-block-attributes';
-export { default as usePost } from './use-post';
-export { default as usePostById } from './use-post-by-id';
-export { default as usePostMeta } from './use-post-meta';
-export { default as usePostMetaValue } from './use-post-meta-value';
-export { default as usePosts } from './use-posts';
-export { default as usePreviewLink } from './use-preview-link';
-export { default as useTerm } from './use-term';
-export { default as useTerms } from './use-terms';
+export { default as useBlockName } from "./use-block-name";
```
Comment (renatonascalves) [inline packages/block-editor-tools/src/hooks/index.js:1]: Good catch. 💯

**Review by srtfisher — APPROVED** [review]
